package telas;

import repositorio.ContaDao;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import model.Conta;

public class LancamentoContas extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form LancamentoContas
     */
    public LancamentoContas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JTextField();
        codgoboleto = new javax.swing.JTextField();
        docnumenro = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vencimento = new comp.JCalendar();
        jLabel3 = new javax.swing.JLabel();
        valor = new Utilitarios.JNumberFormatField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        parcelas = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        cedente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        emissor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtmsn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes da Conta");

        titulo.setBackground(new java.awt.Color(255, 255, 204));

        codgoboleto.setBackground(new java.awt.Color(153, 204, 255));
        codgoboleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codgoboletoKeyReleased(evt);
            }
        });

        docnumenro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                docnumenroFocusGained(evt);
            }
        });

        tipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGAR", "RECEBER" }));

        jLabel1.setText("Tipo:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Vencimento:");

        valor.setBackground(new java.awt.Color(204, 255, 204));
        valor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel4.setText("Doc N°:");

        jLabel5.setText("Valor:");

        jLabel6.setText("Codigo Barras:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jButton1.setText("Registrar Conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        parcelas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        parcelas.setModel(new javax.swing.SpinnerNumberModel(1, null, 24, 1));

        jLabel7.setText("Parcelas:");

        jLabel8.setText("Cedente/Devedor:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clean.png"))); // NOI18N
        jButton2.setText("Nova");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        emissor.setEditable(true);
        emissor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco do Brasil", "Caixa Econômica", "Santander", "Banco Itaú", "Banco Inter", "Bradesco", "Nubank", "Outros" }));

        jLabel9.setText("Banco Emissor:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-24.png"))); // NOI18N

        txtmsn.setBackground(new java.awt.Color(255, 153, 153));
        txtmsn.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo)
                            .addComponent(codgoboleto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(docnumenro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(emissor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cedente)
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton3))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtmsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(2, 2, 2)
                        .addComponent(jButton1)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docnumenro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(codgoboleto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton2))))
                    .addComponent(emissor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (valor.getValue().doubleValue() != 0 && !titulo.getText().equals("")) {
                int p = (Integer) parcelas.getValue();

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

                int dias = 0;

                for (int i = 1; i <= p; i++) {

                    Conta conta = new Conta();
                    switch (tipo.getSelectedItem().toString()) {
                        case "PAGAR":
                            conta.setBanco(emissor.getSelectedItem().toString());
                            conta.setBoletoNumero(codgoboleto.getText());
                            conta.setCendente(cedente.getText());
                            conta.setTitulo(titulo.getText().toUpperCase());
                            conta.setDocNumero(docnumenro.getText());
                            conta.setTipo(tipo.getSelectedItem().toString().toUpperCase());
                            conta.setVencimento(LocalDate.parse(vencimento.getText(), formatter).plusDays(dias));
                            conta.setParcelas(i);
                            conta.setValor(valor.getValue().divide(new BigDecimal(p), 2, RoundingMode.HALF_UP));
                            conta.setStatus(" A PAGAR ");
                            new ContaDao().salva(conta);
                            TelaContas.mostrarContasPagar();
                            this.setVisible(false);
                            break;
                        case "RECEBER":
                            conta.setBanco(emissor.getSelectedItem().toString());
                            conta.setBoletoNumero(codgoboleto.getText());
                            conta.setCendente(cedente.getText());
                            conta.setTitulo(titulo.getText().toUpperCase());
                            conta.setDocNumero(docnumenro.getText());
                            conta.setTipo(tipo.getSelectedItem().toString().toUpperCase());
                            conta.setVencimento(LocalDate.parse(vencimento.getText(), formatter).plusDays(dias));
                            conta.setParcelas(i);
                            conta.setValor(valor.getValue().divide(new BigDecimal(p), 2, RoundingMode.HALF_UP));
                            conta.setStatus(" A RECEBER ");
                            new ContaDao().salva(conta);
                            TelaContas.mostrarContasReceber();
                            this.setVisible(false);
                            break;
                    }

                    dias += 30;

                }
            } else {
                JOptionPane.showMessageDialog(docnumenro, "Atenção", "Informe os dados da conta", 0);
            }
        } catch (PersistenceException e) {
            JOptionPane.showMessageDialog(docnumenro, "Atenção", "Houve um erro devido esse titulo de numero " + docnumenro.getText() + "\nja esta cadastrado.", 0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void codgoboletoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codgoboletoKeyReleased
        String codigo = codgoboleto.getText().trim();

        if (evt.getID() == KeyEvent.KEY_PRESSED && evt.getKeyCode() == KeyEvent.VK_ENTER) {

            System.out.println(codigo);
            System.out.println(evt.getKeyChar());
            System.out.println(evt.getKeyCode());

        }
    }//GEN-LAST:event_codgoboletoKeyReleased

    private void docnumenroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_docnumenroFocusGained
        txtmsn.setText("");
    }//GEN-LAST:event_docnumenroFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println(new ContaDao().getTotalReceber());
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedente;
    private javax.swing.JTextField codgoboleto;
    private javax.swing.JTextField docnumenro;
    private javax.swing.JComboBox<String> emissor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner parcelas;
    public static javax.swing.JComboBox<String> tipo;
    private javax.swing.JTextField titulo;
    public static javax.swing.JLabel txtmsn;
    private Utilitarios.JNumberFormatField valor;
    private comp.JCalendar vencimento;
    // End of variables declaration//GEN-END:variables
}
